### PR TITLE
Why is the update of mash scripts commented out?

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by djw8605** [comment]
I want it automatic, since the first time I ran the update-all-repos.sh, it failed saying: "Need to update mash scripts first".

So my puppet new build of a node failed because this isn't made to work out of the box.

**Comment by djw8605** [comment]
Yup, so I vote:

1. Yes, run out of the box.
2. Eh, up to you.  I'm fine with it running daily.

**Comment by edquist** [comment]
Alright, that's fine with me then.  These changes address (2), but yeah we'll need to add a `%post` section to the rpm for (1), i think.

**Comment by brianhlin** [comment]
What RPM is that? `osg-repo-scripts`?

**Comment by edquist** [comment]
It is `osg-repo-scripts`, yes.  Do we want to add `update_mashfiles.sh` to run in a `%post` section of the rpm?

**Pull request merged**
